export const UPDATESTATE = 'updateState';
export const GETSTATE = 'getState';
export const CLEARSTATE = 'CLEARSTATE';

// 登录注册模块
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';

// 基础信息模块 —— 门店档案
export const GETSHOPLIST = 'GETSHOPLIST';

// 基础信息模块 —— 总部档案
export const GETHQLIST = 'GETHQLIST';

// 基础信息模块 —— 供应商档案
export const GETSUPPLYLIST = 'GETSUPPLYLIST';

// 基础信息模块 —— 物品档案
export const GETGOODSLIST = 'GETGOODSLIST';

// 门店模块 —— 请购
export const GETPURCHASEORDERLIST = 'GETPURCHASEORDERLIST';
export const GETPURCHASEGOODSLIST = 'GETPURCHASEGOODSLIST';
export const GETPURCHASESHOPLIST = 'GETPURCHASESHOPLIST';
export const GETPURCHASEDISPATCHLIST = 'GETPURCHASEDISPATCHLIST';

// 门店模块 —— 自采
export const GETSELFPURCHASEORDERLIST = 'GETSELFPURCHASEORDERLIST';
export const GETSELFPURCHASEGOODSLIST = 'GETSELFPURCHASEGOODSLIST';
export const GETSELFPURCHASESHOPLIST = 'GETSELFPURCHASESHOPLIST';
export const GETSELFPURCHASESUPPLYLIST = 'GETSELFPURCHASESUPPLYLIST';
export const GETPURCHASEACCEPTORDERLIST = 'GETPURCHASEACCEPTORDERLIST';
export const GETGOODSDEPOTLIST = 'GETGOODSDEPOTLIST';

// 总部模块 —— 订单管理
export const GETDISPATCHORDERLIST = 'GETDISPATCHORDERLIST';

// 供应商模块 —— 订单管理
export const GETSENDGOODSORDERLIST = 'GETSENDGOODSORDERLIST';
